


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."sync_tournament_date_to_results"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    -- Verifica se a data realmente mudou para não pesar o banco à toa
    IF (OLD.tournament_date IS DISTINCT FROM NEW.tournament_date) THEN
        UPDATE tournament_results
        SET tournament_date = NEW.tournament_date
        WHERE tournament_id = NEW.id;
    END IF;
    
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."sync_tournament_date_to_results"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."deck_images" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "deck_id" "uuid" NOT NULL,
    "image_url" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."deck_images" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."decks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."decks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."players" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."players" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stores" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."stores" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tournament" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tournament_name" "text",
    "tournament_date" "date",
    "store_id" "uuid",
    "total_players" smallint,
    "instagram_link" "text"
);


ALTER TABLE "public"."tournament" OWNER TO "postgres";


ALTER TABLE "public"."tournament" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tournament_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tournament_results" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "store_id" "uuid" NOT NULL,
    "tournament_date" "date" NOT NULL,
    "total_players" smallint NOT NULL,
    "placement" smallint NOT NULL,
    "deck_id" "uuid" NOT NULL,
    "decklist_link" "text",
    "player_id" "uuid",
    "tournament_id" bigint,
    CONSTRAINT "placement_valid" CHECK (("placement" <= "total_players")),
    CONSTRAINT "tournament_results_placement_check" CHECK (("placement" > 0)),
    CONSTRAINT "tournament_results_total_players_check" CHECK (("total_players" > 0))
);


ALTER TABLE "public"."tournament_results" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."v_deck_representation" AS
 SELECT "d"."name" AS "deck",
    "count"(*) AS "appearances"
   FROM ("public"."tournament_results" "tr"
     JOIN "public"."decks" "d" ON (("d"."id" = "tr"."deck_id")))
  GROUP BY "d"."name"
  ORDER BY ("count"(*)) DESC;


ALTER VIEW "public"."v_deck_representation" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."v_deck_stats" AS
 SELECT "d"."name" AS "deck",
    "count"(*) AS "top4_total",
    "sum"(
        CASE
            WHEN ("tr"."placement" = 1) THEN 1
            ELSE 0
        END) AS "titles"
   FROM ("public"."tournament_results" "tr"
     JOIN "public"."decks" "d" ON (("tr"."deck_id" = "d"."id")))
  GROUP BY "d"."name"
  ORDER BY ("sum"(
        CASE
            WHEN ("tr"."placement" = 1) THEN 1
            ELSE 0
        END)) DESC;


ALTER VIEW "public"."v_deck_stats" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."v_meta_by_month" AS
 SELECT "date_trunc"('month'::"text", ("tr"."tournament_date")::timestamp with time zone) AS "month",
    "d"."name" AS "deck",
    "count"(*) AS "appearances"
   FROM ("public"."tournament_results" "tr"
     JOIN "public"."decks" "d" ON (("d"."id" = "tr"."deck_id")))
  GROUP BY ("date_trunc"('month'::"text", ("tr"."tournament_date")::timestamp with time zone)), "d"."name"
  ORDER BY ("date_trunc"('month'::"text", ("tr"."tournament_date")::timestamp with time zone)) DESC, ("count"(*)) DESC;


ALTER VIEW "public"."v_meta_by_month" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."v_monthly_ranking" AS
 SELECT "date_trunc"('month'::"text", ("tr"."tournament_date")::timestamp with time zone) AS "month",
    "p"."name" AS "player",
    "sum"(
        CASE "tr"."placement"
            WHEN 1 THEN 4
            WHEN 2 THEN 3
            WHEN 3 THEN 2
            WHEN 4 THEN 1
            ELSE NULL::integer
        END) AS "points"
   FROM ("public"."tournament_results" "tr"
     JOIN "public"."players" "p" ON (("tr"."player_id" = "p"."id")))
  GROUP BY ("date_trunc"('month'::"text", ("tr"."tournament_date")::timestamp with time zone)), "p"."name"
  ORDER BY ("date_trunc"('month'::"text", ("tr"."tournament_date")::timestamp with time zone)) DESC, ("sum"(
        CASE "tr"."placement"
            WHEN 1 THEN 4
            WHEN 2 THEN 3
            WHEN 3 THEN 2
            WHEN 4 THEN 1
            ELSE NULL::integer
        END)) DESC;


ALTER VIEW "public"."v_monthly_ranking" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."v_player_ranking" AS
 SELECT "p"."name" AS "player",
    "count"(*) AS "top4_total",
    "sum"(
        CASE
            WHEN ("tr"."placement" = 1) THEN 1
            ELSE 0
        END) AS "titles",
    "sum"(
        CASE "tr"."placement"
            WHEN 1 THEN 4
            WHEN 2 THEN 3
            WHEN 3 THEN 2
            WHEN 4 THEN 1
            ELSE NULL::integer
        END) AS "ranking_points"
   FROM ("public"."tournament_results" "tr"
     JOIN "public"."players" "p" ON (("tr"."player_id" = "p"."id")))
  GROUP BY "p"."name"
  ORDER BY ("sum"(
        CASE "tr"."placement"
            WHEN 1 THEN 4
            WHEN 2 THEN 3
            WHEN 3 THEN 2
            WHEN 4 THEN 1
            ELSE NULL::integer
        END)) DESC;


ALTER VIEW "public"."v_player_ranking" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."v_podium" AS
 SELECT "tr"."id",
    "s"."name" AS "store",
    "tr"."tournament_date",
    "tr"."placement",
    "p"."name" AS "player",
    "d"."name" AS "deck"
   FROM ((("public"."tournament_results" "tr"
     JOIN "public"."stores" "s" ON (("tr"."store_id" = "s"."id")))
     JOIN "public"."decks" "d" ON (("tr"."deck_id" = "d"."id")))
     LEFT JOIN "public"."players" "p" ON (("tr"."player_id" = "p"."id")));


ALTER VIEW "public"."v_podium" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."v_podium_full" AS
 SELECT "tr"."id",
    "tr"."store_id",
    "s"."name" AS "store",
    "tr"."tournament_date",
    "tr"."placement",
    "p"."name" AS "player",
    "d"."name" AS "deck",
    "di"."image_url",
    "tr"."total_players"
   FROM (((("public"."tournament_results" "tr"
     JOIN "public"."stores" "s" ON (("tr"."store_id" = "s"."id")))
     JOIN "public"."decks" "d" ON (("tr"."deck_id" = "d"."id")))
     LEFT JOIN "public"."players" "p" ON (("tr"."player_id" = "p"."id")))
     LEFT JOIN "public"."deck_images" "di" ON (("di"."deck_id" = "d"."id")));


ALTER VIEW "public"."v_podium_full" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."v_store_champions" AS
 SELECT "s"."name" AS "store",
    "p"."name" AS "player",
    "count"(*) AS "titles"
   FROM (("public"."tournament_results" "tr"
     JOIN "public"."stores" "s" ON (("tr"."store_id" = "s"."id")))
     JOIN "public"."players" "p" ON (("tr"."player_id" = "p"."id")))
  WHERE ("tr"."placement" = 1)
  GROUP BY "s"."name", "p"."name"
  ORDER BY "s"."name", ("count"(*)) DESC;


ALTER VIEW "public"."v_store_champions" OWNER TO "postgres";


ALTER TABLE ONLY "public"."deck_images"
    ADD CONSTRAINT "deck_images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."decks"
    ADD CONSTRAINT "decks_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."decks"
    ADD CONSTRAINT "decks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stores"
    ADD CONSTRAINT "stores_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."stores"
    ADD CONSTRAINT "stores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tournament"
    ADD CONSTRAINT "tournament_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tournament_results"
    ADD CONSTRAINT "tournament_results_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tournament_results"
    ADD CONSTRAINT "unique_player_per_tournament" UNIQUE ("store_id", "tournament_date", "player_id");



ALTER TABLE ONLY "public"."tournament_results"
    ADD CONSTRAINT "unique_tournament_placement" UNIQUE ("store_id", "tournament_date", "placement");



CREATE INDEX "idx_results_date" ON "public"."tournament_results" USING "btree" ("tournament_date");



CREATE INDEX "idx_results_deck" ON "public"."tournament_results" USING "btree" ("deck_id");



CREATE INDEX "idx_results_store" ON "public"."tournament_results" USING "btree" ("store_id");



CREATE INDEX "idx_top8_results" ON "public"."tournament_results" USING "btree" ("placement") WHERE ("placement" <= 8);



CREATE OR REPLACE TRIGGER "trg_sync_date_after_tournament_update" AFTER UPDATE OF "tournament_date" ON "public"."tournament" FOR EACH ROW EXECUTE FUNCTION "public"."sync_tournament_date_to_results"();



ALTER TABLE ONLY "public"."deck_images"
    ADD CONSTRAINT "fk_deck" FOREIGN KEY ("deck_id") REFERENCES "public"."decks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tournament_results"
    ADD CONSTRAINT "fk_deck" FOREIGN KEY ("deck_id") REFERENCES "public"."decks"("id");



ALTER TABLE ONLY "public"."tournament_results"
    ADD CONSTRAINT "fk_player" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id");



ALTER TABLE ONLY "public"."tournament_results"
    ADD CONSTRAINT "fk_store" FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id");



ALTER TABLE ONLY "public"."tournament_results"
    ADD CONSTRAINT "tournament_results_tournament_id_fkey" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournament"("id");



ALTER TABLE ONLY "public"."tournament"
    ADD CONSTRAINT "tournament_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id");



CREATE POLICY "Allow anonymous delete" ON "public"."deck_images" FOR DELETE USING (true);



CREATE POLICY "Allow anonymous delete" ON "public"."decks" FOR DELETE USING (true);



CREATE POLICY "Allow anonymous delete" ON "public"."tournament_results" FOR DELETE TO "anon" USING (true);



CREATE POLICY "Allow anonymous insert" ON "public"."deck_images" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow anonymous insert" ON "public"."decks" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow anonymous insert" ON "public"."tournament" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow anonymous insert" ON "public"."tournament_results" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "Allow anonymous select" ON "public"."deck_images" FOR SELECT USING (true);



CREATE POLICY "Allow anonymous select" ON "public"."decks" FOR SELECT USING (true);



CREATE POLICY "Allow anonymous select" ON "public"."tournament" FOR SELECT USING (true);



CREATE POLICY "Allow anonymous select" ON "public"."tournament_results" FOR SELECT TO "anon" USING (true);



CREATE POLICY "Allow anonymous update" ON "public"."deck_images" FOR UPDATE USING (true);



CREATE POLICY "Allow anonymous update" ON "public"."decks" FOR UPDATE USING (true);



CREATE POLICY "Allow anonymous update" ON "public"."tournament" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Allow anonymous update" ON "public"."tournament_results" FOR UPDATE TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "Allow public delete" ON "public"."players" FOR DELETE USING (true);



CREATE POLICY "Allow public insert" ON "public"."players" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public select" ON "public"."players" FOR SELECT USING (true);



CREATE POLICY "Allow public update" ON "public"."players" FOR UPDATE USING (true);



CREATE POLICY "Public insert tournament results" ON "public"."tournament_results" FOR INSERT WITH CHECK (true);



CREATE POLICY "Public read deck images" ON "public"."deck_images" FOR SELECT USING (true);



CREATE POLICY "Public read decks" ON "public"."decks" FOR SELECT USING (true);



CREATE POLICY "Public read results" ON "public"."tournament_results" FOR SELECT USING (true);



CREATE POLICY "Public read stores" ON "public"."stores" FOR SELECT USING (true);



CREATE POLICY "Public read tournament results" ON "public"."tournament_results" FOR SELECT USING (true);



ALTER TABLE "public"."deck_images" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."decks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."players" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tournament" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tournament_results" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."sync_tournament_date_to_results"() TO "anon";
GRANT ALL ON FUNCTION "public"."sync_tournament_date_to_results"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."sync_tournament_date_to_results"() TO "service_role";



GRANT ALL ON TABLE "public"."deck_images" TO "anon";
GRANT ALL ON TABLE "public"."deck_images" TO "authenticated";
GRANT ALL ON TABLE "public"."deck_images" TO "service_role";



GRANT ALL ON TABLE "public"."decks" TO "anon";
GRANT ALL ON TABLE "public"."decks" TO "authenticated";
GRANT ALL ON TABLE "public"."decks" TO "service_role";



GRANT ALL ON TABLE "public"."players" TO "anon";
GRANT ALL ON TABLE "public"."players" TO "authenticated";
GRANT ALL ON TABLE "public"."players" TO "service_role";



GRANT ALL ON TABLE "public"."stores" TO "anon";
GRANT ALL ON TABLE "public"."stores" TO "authenticated";
GRANT ALL ON TABLE "public"."stores" TO "service_role";



GRANT ALL ON TABLE "public"."tournament" TO "anon";
GRANT ALL ON TABLE "public"."tournament" TO "authenticated";
GRANT ALL ON TABLE "public"."tournament" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tournament_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tournament_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tournament_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tournament_results" TO "anon";
GRANT ALL ON TABLE "public"."tournament_results" TO "authenticated";
GRANT ALL ON TABLE "public"."tournament_results" TO "service_role";



GRANT ALL ON TABLE "public"."v_deck_representation" TO "anon";
GRANT ALL ON TABLE "public"."v_deck_representation" TO "authenticated";
GRANT ALL ON TABLE "public"."v_deck_representation" TO "service_role";



GRANT ALL ON TABLE "public"."v_deck_stats" TO "anon";
GRANT ALL ON TABLE "public"."v_deck_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."v_deck_stats" TO "service_role";



GRANT ALL ON TABLE "public"."v_meta_by_month" TO "anon";
GRANT ALL ON TABLE "public"."v_meta_by_month" TO "authenticated";
GRANT ALL ON TABLE "public"."v_meta_by_month" TO "service_role";



GRANT ALL ON TABLE "public"."v_monthly_ranking" TO "anon";
GRANT ALL ON TABLE "public"."v_monthly_ranking" TO "authenticated";
GRANT ALL ON TABLE "public"."v_monthly_ranking" TO "service_role";



GRANT ALL ON TABLE "public"."v_player_ranking" TO "anon";
GRANT ALL ON TABLE "public"."v_player_ranking" TO "authenticated";
GRANT ALL ON TABLE "public"."v_player_ranking" TO "service_role";



GRANT ALL ON TABLE "public"."v_podium" TO "anon";
GRANT ALL ON TABLE "public"."v_podium" TO "authenticated";
GRANT ALL ON TABLE "public"."v_podium" TO "service_role";



GRANT ALL ON TABLE "public"."v_podium_full" TO "anon";
GRANT ALL ON TABLE "public"."v_podium_full" TO "authenticated";
GRANT ALL ON TABLE "public"."v_podium_full" TO "service_role";



GRANT ALL ON TABLE "public"."v_store_champions" TO "anon";
GRANT ALL ON TABLE "public"."v_store_champions" TO "authenticated";
GRANT ALL ON TABLE "public"."v_store_champions" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







