-- Private feedback inbox populated only by the send-feedback Edge Function.

BEGIN;

CREATE TABLE IF NOT EXISTS public.feedback_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id uuid NOT NULL UNIQUE,
    feedback_type text NOT NULL CHECK (feedback_type IN ('bug', 'suggestion')),
    subject text NOT NULL,
    message text NOT NULL CHECK (char_length(message) BETWEEN 10 AND 5000),
    contact_email text,
    page_url text,
    app_version text,
    user_agent text,
    client_hash text,
    status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'sent', 'failed')),
    provider_message_id text,
    email_sent_at timestamptz,
    email_error text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_feedback_submissions_created_at
    ON public.feedback_submissions (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_feedback_submissions_client_hash
    ON public.feedback_submissions (client_hash, created_at DESC);

ALTER TABLE public.feedback_submissions ENABLE ROW LEVEL SECURITY;

-- No anon/authenticated policies or grants: browser access is intentionally denied.
REVOKE ALL ON public.feedback_submissions FROM anon, authenticated;
GRANT ALL ON public.feedback_submissions TO service_role;
GRANT ALL ON SEQUENCE public.feedback_submissions_id_seq TO service_role;

COMMIT;
