-- Optional Bandai TCG+ OCR evidence and per-player match points.

BEGIN;

ALTER TABLE public.tournament_results
    ADD COLUMN IF NOT EXISTS match_points integer;

ALTER TABLE public.tournament_results
    DROP CONSTRAINT IF EXISTS tournament_results_match_points_check;

ALTER TABLE public.tournament_results
    ADD CONSTRAINT tournament_results_match_points_check
    CHECK (match_points IS NULL OR match_points >= 0);

CREATE TABLE IF NOT EXISTS public.tournament_ocr_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id bigint NOT NULL
        REFERENCES public.tournament(id) ON DELETE CASCADE,
    batch_id uuid NOT NULL,
    storage_path text NOT NULL UNIQUE,
    original_name text NOT NULL,
    mime_type text,
    size_bytes bigint CHECK (size_bytes IS NULL OR size_bytes >= 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tournament_ocr_files_tournament_id
    ON public.tournament_ocr_files (tournament_id, created_at);

ALTER TABLE public.tournament_ocr_files ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read tournament OCR files" ON public.tournament_ocr_files;
CREATE POLICY "Public read tournament OCR files"
    ON public.tournament_ocr_files FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Public insert tournament OCR files" ON public.tournament_ocr_files;
CREATE POLICY "Public insert tournament OCR files"
    ON public.tournament_ocr_files FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS "Public delete tournament OCR files" ON public.tournament_ocr_files;
CREATE POLICY "Public delete tournament OCR files"
    ON public.tournament_ocr_files FOR DELETE
    TO anon, authenticated
    USING (true);

GRANT SELECT, INSERT, DELETE ON public.tournament_ocr_files TO anon, authenticated;
GRANT ALL ON public.tournament_ocr_files TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.tournament_ocr_files_id_seq TO anon, authenticated;
GRANT ALL ON SEQUENCE public.tournament_ocr_files_id_seq TO service_role;

INSERT INTO storage.buckets (id, name, public)
VALUES ('tournament-ocr-sources', 'tournament-ocr-sources', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

DROP POLICY IF EXISTS "Public read tournament OCR sources" ON storage.objects;
CREATE POLICY "Public read tournament OCR sources"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'tournament-ocr-sources');

DROP POLICY IF EXISTS "Public upload tournament OCR sources" ON storage.objects;
CREATE POLICY "Public upload tournament OCR sources"
    ON storage.objects FOR INSERT
    TO anon, authenticated
    WITH CHECK (bucket_id = 'tournament-ocr-sources');

DROP POLICY IF EXISTS "Public delete tournament OCR sources" ON storage.objects;
CREATE POLICY "Public delete tournament OCR sources"
    ON storage.objects FOR DELETE
    TO anon, authenticated
    USING (bucket_id = 'tournament-ocr-sources');

CREATE OR REPLACE VIEW public.v_podium_full
WITH (security_invoker = true) AS
SELECT
    tr.id,
    tr.store_id,
    s.name AS store,
    tr.tournament_date,
    tr.placement,
    p.name AS player,
    d.name AS deck,
    di.image_url,
    tr.total_players,
    tr.tournament_id,
    tr.decklist,
    t.tournament_name,
    t.instagram_link,
    COALESCE(f.code, 'UNSPECIFIED') AS format_code,
    tr.match_points
FROM public.tournament_results tr
JOIN public.stores s ON s.id = tr.store_id
LEFT JOIN public.decks d ON d.id = tr.deck_id
LEFT JOIN public.players p ON p.id = tr.player_id
LEFT JOIN public.tournament t ON t.id = tr.tournament_id
LEFT JOIN public.formats f ON f.id = t.format_id
LEFT JOIN LATERAL (
    SELECT dimg.image_url
    FROM public.deck_images dimg
    WHERE dimg.deck_id = d.id
    ORDER BY dimg.created_at DESC, dimg.id DESC
    LIMIT 1
) di ON true;

GRANT ALL ON TABLE public.v_podium_full TO anon, authenticated, service_role;

COMMIT;
