-- Formats catalog with single default format support.
-- Run in Supabase SQL editor.

CREATE TABLE IF NOT EXISTS public.formats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text,
    background_path text,
    background_url text,
    is_active boolean NOT NULL DEFAULT true,
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.formats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous select formats" ON public.formats;
CREATE POLICY "Allow anonymous select formats" ON public.formats
    FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow anonymous insert formats" ON public.formats;
CREATE POLICY "Allow anonymous insert formats" ON public.formats
    FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous update formats" ON public.formats;
CREATE POLICY "Allow anonymous update formats" ON public.formats
    FOR UPDATE
    USING (true)
    WITH CHECK (true);

CREATE UNIQUE INDEX IF NOT EXISTS uq_formats_single_default
    ON public.formats (is_default)
    WHERE is_default = true;

CREATE OR REPLACE FUNCTION public.ensure_single_default_format()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.is_default THEN
        UPDATE public.formats
        SET is_default = false
        WHERE id <> COALESCE(NEW.id, -1)
          AND is_default = true;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_formats_single_default ON public.formats;
CREATE TRIGGER trg_formats_single_default
BEFORE INSERT OR UPDATE OF is_default
ON public.formats
FOR EACH ROW
EXECUTE FUNCTION public.ensure_single_default_format();

ALTER TABLE public.tournament
    ADD COLUMN IF NOT EXISTS format text;

INSERT INTO public.formats (code, name, background_path, is_active, is_default)
VALUES
    ('BT23', 'BT23', 'BT23.png', true, false),
    ('BT24', 'BT24', 'BT24.png', true, true),
    ('EX11', 'EX11', 'EX11.png', true, false)
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    background_path = EXCLUDED.background_path,
    is_active = EXCLUDED.is_active;

UPDATE public.formats
SET is_default = (code = 'BT24');

UPDATE public.tournament t
SET format = f.code
FROM public.formats f
WHERE f.is_default = true
  AND (t.format IS NULL OR btrim(t.format) = '');
